DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS online_order;

CREATE TABLE item (
  sku TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  qty INTEGER NOT NULL
);

CREATE TABLE online_order (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  detail TEXT NOT NULL,
  item_names TEXT NOT NULL,
  total_price REAL NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);